### PR TITLE
Adding support to Office keys.

### PR DESCRIPTION
**Pull request by shsouza**

### CODE REVIEW

**Comment by mrpeardotnet** [comment]
Hi, I've tested your Office key retrieval code, but it does not work with my Office 2013...

var key = RegistryKey
                .OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry32)
                .OpenSubKey(keyPath);

Key is NULL.

Have you tested it for Office 2013? Does Office 2013 nad up store it the same way as 2010? Does not look so...

**Comment by mrpeardotnet** [comment]
No, Office 2013 and up is not storing product id in the registry!!!

**Comment by shsouza** [comment]
Hi, I tested successfuly on office 2003, now i'm working on another versions... already known that have a offset on digitalproductid on version 14 and up.

**Comment by mrpeardotnet** [comment]
Version 2013 (15) and up does not store product id in the registry, so your solution works only for version 2010 and down... This is probably why there is no Office 2013 or 2016 product key decoder available (as far I have been searching the net).

**Comment by mrpeardotnet** [comment]
Please, please, please... What does "Add Office 2013 support" mean? Have you tested it with Office 2013? Have you read my previous comments?

You are still trying to get Registration from Registry, but

`var digitalProductId = result.FindValueNameByName("DigitalProductId");`

returns NULL, because THERE IS NO DigitalProductId in registry for Office 2013 or up!

**Comment by shsouza** [comment]
Hi, doing some research i found a vbscript with support do 2013.... but I think which it depends on the tyoe of licensing.

I tested sucessfully with office 2003,2007,2010,2013.

**Comment by mrpeardotnet** [comment]
Well it does not work with my Office 2013 installed. Why dont you link me that VBS script?

**Comment by shsouza** [comment]
[MicrosoftKeyFinder.vbs.txt](https://github.com/mrpeardotnet/WinProdKeyFinder/files/476767/MicrosoftKeyFinder.vbs.txt)

**Pull request closed without merging**
